### ISSUE TITLE
Problem opening xpcs_viewer from Windows

### ISSUE THREAD

**Issue by qzhang234** [AdvancedPhotonSource/pyXpcsViewer#13]
Opening `xpcs_viewer` from Windows produced the following error message on the terminal:

<details>
<summary> Terminal output  </summary>

```


(VirEnv) PS D:\Work\Projects\Piotr_XPCS\A021_Silica_D100nm_att3_Rq0_R> run_viewer

D:\Work\Projects\Piotr_XPCS\A021_Silica_D100nm_att3_Rq0_R>python -c "from xpcs_viewer import run; run()" $@
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\qzhang234\Anaconda3\envs\VirEnv\lib\site-packages\xpcs_viewer\__init__.py", line 2, in <module>
    from .viewer import run
  File "C:\Users\qzhang234\Anaconda3\envs\VirEnv\lib\site-packages\xpcs_viewer\viewer.py", line 2, in <module>
    from .viewer_ui import Ui_mainWindow as Ui
  File "C:\Users\qzhang234\Anaconda3\envs\VirEnv\lib\site-packages\xpcs_viewer\viewer_ui.py", line 1695, in <module>
    from .plothandler import ImageViewDev, MplCanvasBarH, MplCanvasBarV, PlotWidgetDev
  File "C:\Users\qzhang234\Anaconda3\envs\VirEnv\lib\site-packages\xpcs_viewer\plothandler\__init__.py", line 2, in <module>
    from .pyqtgraph_handler import ImageViewDev, PlotWidgetDev
  File "C:\Users\qzhang234\Anaconda3\envs\VirEnv\lib\site-packages\xpcs_viewer\plothandler\pyqtgraph_handler.py", line 1, in <module>
    import pyqtgraph as pg
  File "C:\Users\qzhang234\Anaconda3\envs\VirEnv\lib\site-packages\pyqtgraph\__init__.py", line 13, in <module>
    from .Qt import QtGui, mkQApp
  File "C:\Users\qzhang234\Anaconda3\envs\VirEnv\lib\site-packages\pyqtgraph\Qt.py", line 140, in <module>
    from PyQt5 import QtSvg
ValueError: PyCapsule_GetPointer called with incorrect name
(VirEnv) PS D:\Work\Projects\Piotr_XPCS\A021_Silica_D100nm_att3_Rq0_R>

```

</details>

**Comment by qzhang234** [comment]
Solved
