### ISSUE TITLE
Problem opening xpcs-viewer from qzhang234 on kouga1g

### ISSUE THREAD

**Issue by qzhang234** [AdvancedPhotonSource/pyXpcsViewer#14]
I tried to open `xpcs_viewer` when logged in as `qzhang234` on kouga1g, and I got the following error message. Any suggestions?

<details>
<summary> Terminal prompt </summary>

```

(QZ_09_12_19) bash-4.2$ 
(QZ_09_12_19) bash-4.2$ xpcs_viewer 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/beams10/8IDIUSER/Documents/Miaoqi/xpcs_gui/xpcs_viewer/__init__.py", line 2, in <module>
    from .viewer import run 
  File "/home/beams10/8IDIUSER/Documents/Miaoqi/xpcs_gui/xpcs_viewer/viewer.py", line 2, in <module>
    from .viewer_ui import Ui_mainWindow as Ui
  File "/home/beams10/8IDIUSER/Documents/Miaoqi/xpcs_gui/xpcs_viewer/viewer_ui.py", line 1695, in <module>
    from .plothandler import ImageViewDev, MplCanvasBarH, MplCanvasBarV, PlotWidgetDev
  File "/home/beams10/8IDIUSER/Documents/Miaoqi/xpcs_gui/xpcs_viewer/plothandler/__init__.py", line 1, in <module>
    from .matplot_qt import MplCanvasBarH, MplCanvasBarV, MplCanvasBar, MplCanvas
  File "/home/beams10/8IDIUSER/Documents/Miaoqi/xpcs_gui/xpcs_viewer/plothandler/matplot_qt.py", line 1, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
  File "/APSshare/anaconda3/x86_64/lib/python3.7/site-packages/matplotlib/__init__.py", line 174, in <module>
    _check_versions()
  File "/APSshare/anaconda3/x86_64/lib/python3.7/site-packages/matplotlib/__init__.py", line 159, in _check_versions
    from . import ft2font
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /APSshare/anaconda3/x86_64/lib/python3.7/site-packages/matplotlib/ft2font.cpython-37m-x86_64-linux-gnu.so)
(QZ_09_12_19) bash-4.2$ which python
/APSshare/anaconda3/x86_64/bin/python
(QZ_09_12_19) bash-4.2$ 


```

</summary>

**Comment by qzhang234** [comment]
Solved by installing a new conda virtual environment
