### ISSUE TITLE
Metadata not showing for reanalyzed hdf results

### ISSUE THREAD

**Issue by qzhang234** [AdvancedPhotonSource/pyXpcsViewer#18]
![image](https://user-images.githubusercontent.com/48140482/150211158-16821d88-6581-4509-a416-3d2e5a6ce59e.png)

**Comment by qzhang234** [comment]
Error message from terminal:

```

kouga% xpcs_viewer 
2022-01-19 17:42:42,485 xpcs_viewer.viewer      : Maximal threads: 20
2022-01-19 17:42:42,486 xpcs_viewer.viewer      : Start up directory is [/home/8ididata/2021-3/tingxu202111/cluster_results_test]
2022-01-19 17:42:42,487 xpcs_viewer.viewer      : set mainwindow to size (1024, 800)
2022-01-19 17:42:46,471 xpcs_viewer.file_locator: length of target = 1
2022-01-19 17:42:46,476 xpcs_viewer.viewer      : loading hdf files into RAM
2022-01-19 17:42:46,562 xpcs_viewer.viewer      : switch to tab 0: saxs_2d
2022-01-19 17:42:49,886 xpcs_viewer.viewer      : switch to tab 8: metadata
2022-01-19 17:42:50,030 xpcs_viewer.viewer      : Uncaught exception
Traceback (most recent call last):
  File "/APSshare/anaconda3/x86_64/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
numpy.core._exceptions._UFuncOutputCastingError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('bool') with casting rule 'same_kind'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/beams10/8IDIUSER/Documents/Miaoqi/xpcs_gui/xpcs_viewer/viewer.py", line 268, in show_hdf_info
    msg = self.vk.get_hdf_info(fname, filter_str)
  File "/home/beams10/8IDIUSER/Documents/Miaoqi/xpcs_gui/xpcs_viewer/file_locator.py", line 192, in get_hdf_info
    return self.cache[fname].get_hdf_info(fstr)
  File "/home/beams10/8IDIUSER/Documents/Miaoqi/xpcs_gui/xpcs_viewer/xpcs_file.py", line 109, in get_hdf_info
    self.hdf_info = get_hdf_info(self.cwd, self.fname)
  File "/home/beams10/8IDIUSER/Documents/Miaoqi/xpcs_gui/xpcs_viewer/fileIO/hdf_to_str.py", line 91, in get_hdf_info
    res = read_h5py(hdl, '.', 0, '')
  File "/home/beams10/8IDIUSER/Documents/Miaoqi/xpcs_gui/xpcs_viewer/fileIO/hdf_to_str.py", line 77, in read_h5py
    info = read_h5py(hdl, new_path, level + 1, guide_nxt)
  File "/home/beams10/8IDIUSER/Documents/Miaoqi/xpcs_gui/xpcs_viewer/fileIO/hdf_to_str.py", line 77, in read_h5py
    info = read_h5py(hdl, new_path, level + 1, guide_nxt)
  File "/home/beams10/8IDIUSER/Documents/Miaoqi/xpcs_gui/xpcs_viewer/fileIO/hdf_to_str.py", line 60, in read_h5py
    info = describe_numpy(np.array(hdl[path]))
  File "/home/beams10/8IDIUSER/Documents/Miaoqi/xpcs_gui/xpcs_viewer/fileIO/hdf_to_str.py", line 29, in describe_numpy
    repr += 'minmax = %s, mean = %s' % (c2r(res.minmax),
  File "/home/beams10/8IDIUSER/Documents/Miaoqi/xpcs_gui/xpcs_viewer/fileIO/hdf_to_str.py", line 21, in c2r
    res = str(np.round(x, 3))
  File "<__array_function__ internals>", line 6, in round_
  File "/APSshare/anaconda3/x86_64/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 3718, in round_
    return around(a, decimals=decimals, out=out)
  File "<__array_function__ internals>", line 6, in around
  File "/APSshare/anaconda3/x86_64/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 3293, in around
    return _wrapfunc(a, 'round', decimals=decimals, out=out)
  File "/APSshare/anaconda3/x86_64/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 67, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/APSshare/anaconda3/x86_64/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 44, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
numpy.core._exceptions._UFuncOutputCastingError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('bool') with casting rule 'same_kind'

```

**Comment by AZjk** [comment]
mask generated with the new tool is a numpy-bool array. should work now @qzhang234 . please comfirm

**Comment by qzhang234** [comment]
Yes, I confirm it works. Closing the issue now
